name: Lint

on: [push, pull_request]

jobs:
  xml-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Download schema
      run: wget https://raw.githubusercontent.com/Mearman/unraid-template-schema/master/unraid.xsd
    - name: Lint OctoPrint.xml
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./OctoPrint/OctoPrint.xml
        xml-schema-file: ./unraid.xsd
